### PR TITLE
fix files after cleaning whitespaces

### PR DESCRIPTION
**Pull request by besser82**
Unfortunately some JPEG-files have been corrupted when cleaning up whitespaces in previous #11.

### CODE REVIEW

**Comment by besser82** [comment]
Please merge this one, before preparing a new release…  =)

**Comment by besser82** [comment]
Thank you! ^_^

**Comment by wangmu0701** [comment]
Thank you for all the changes :).
And I updated the version to 1.0.10 in configure.ac.


On Thu, Feb 25, 2016 at 5:57 AM, Björn Esser <notifications@github.com>
wrote:

> Thank you! ^_^
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CSCsw/ColPack/pull/12#issuecomment-188726054>.
>



-- 
Mu Wang, Ph.D. Candidate
HASS 257, Department of Computer Science
Purdue University -- West Lafayette
wangmu0701@gmail.com

**Comment by besser82** [comment]
Thank you!

Could you please tag a release?  It's pretty simple, just use:
`git tag v1.0.10 ffa4e4130011537bdc4658ebb78ab3088f0ea6dc && git push origin --tags`

**Comment by wangmu0701** [comment]
Done, and new skill learned. Thanks! XD

On Thu, Feb 25, 2016 at 6:21 AM, Björn Esser <notifications@github.com>
wrote:

> Thank you!
>
> Could you please tag a release? It's pretty simple, just use:
> git tag v1.0.10 ffa4e4130011537bdc4658ebb78ab3088f0ea6dc && git push
> origin --tags
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CSCsw/ColPack/pull/12#issuecomment-188737685>.
>



-- 
Mu Wang, Ph.D. Candidate
HASS 257, Department of Computer Science
Purdue University -- West Lafayette
wangmu0701@gmail.com

**Pull request merged**
