### PR TITLE
Support CMake (without removing autotools files).

### PR DESCRIPTION
**Pull request by chrisdembia**
Dear authors of ColPack. This PR introduces CMake files so that ColPack can be built with CMake, and in particular, can be easily built with Visual Studio on Windows. The work by @bonh in #9 was useful for starting this PR; however, unlike in #9, I chose to leave the source code in its existing organization, and to not delete the autotools files.

I tried to replicate the behavior and settings from autotools as best I could:

- Users can use the `ENABLE_EXAMPLES` and `ENABLE_OPENMP` options just as with autotools.
- Users can run tests (the SampleDrivers/Basic executables) using ctest.
- Both static and dynamic libraries are built.

I also added documentation to the README on how to use CMake, and I attempted to edit the Travis CI build to also test CMake.

I tested the CMake build system on Mac and Windows (Visual Studio 2015), and have ensured that I can use ColPack in a downstream project.

There are definitely some differences between using CMake and autotools; see the comments in the CMakeLists.txt for more information.

### CODE REVIEW

**Comment by bonh** [comment]
Great work! I will test this approach on "Konrad" of HLRN/ZIB (http://www.zib.de/research_services/supercomputing) in the next days.

**Comment by chrisdembia** [comment]
@wangmu0701 please let know how we can proceed with this.

**Comment by chrisdembia** [comment]
If #18 is merged, I can edit this PR to conform to the new layout.

**Comment by chrisdembia** [comment]
Thanks @wangmu0701

**Pull request merged**
